version: '3.7'

services:
  smoke_tests:
    build:
      context: ${PWD}/
    command: 'source /etc/profile.d/rvm.sh && rvm use 3.0.3 && bundle exec sidekiq -r ./sidekiq/config.rb'
    environment:
      REDIS_URL: redis://redis
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
      - .:/app
    depends_on:
      - redis

  redis:
    image: 'redis:6.2.6'