name: Frontend smoke tests

# Controls when the workflow will run
on: [push]
  # schedule:
  #   - cron: '*/15 8-17 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      API_STAGE: 'production'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: List out environment variables
        run: env

      - name: Run smoke tests using Cypress
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
        timeout-minutes: 8
        continue-on-error: true

      - name: 'Post Cypress failures to Slack'
        uses: communitiesuk/post-cypress-failures-to-slack@main
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'bot-testing'
          message-text: 'Frontend smoke tests failed - videos in :thread:'

      # - name: 'Upload screenshots and videos to Slack'
      #   uses: trymbill/cypress-slack-video-upload-action@v1.3.0
      #   with:
      #     token: ${{ secrets.SLACK_TOKEN }}
      #     channels: 'bot-testing'
      #     message-text: 'Frontend smoke tests failed - videos in :thread:'
