name: Frontend smoke tests

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 8-18 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Also run on a push
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      CYPRESS_API_STAGE: 'production'
      # delay each command by 250ms in order to avoid triggering DDoS protection
      CYPRESS_COMMAND_DELAY: 250

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run smoke tests using Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
        timeout-minutes: 8

      - name: 'Post Cypress failures to Slack'
        uses: communitiesuk/epb-post-cypress-failures-to-slack@v1
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: 'team-epb'
          message-text: '🔥 EPB Frontend smoke test failure'

      - name: 'Write a dummy commit to keep smoke tests alive if needed'
        uses: gautamkrishnar/keepalive-workflow@v1
